name: Check Secrets

on:
  push:
    branches:
      - main

jobs:
  check-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Display Client ID
      run: echo "Client ID: ${{ secrets.CLIENT_ID }}"
