name: Check Secrets

on:
  push:
    branches:
      - main

jobs:
  check-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Display Refresh Token
      run: |
        REFRESH_TOKEN=${{ secrets.REFRESH_TOKEN }}
        echo "Refresh Token: $REFRESH_TOKEN"
        if [ "$REFRESH_TOKEN" == "1//04MoJ89JCpVwjCgYIARAAGAQSNwF-L9IrUAUgS5LhTZ2ZsoHnteuzqBMi3_8L3SQ9dDbAkCjNuGm-USsghLVw9vSnngC23-5Nd8o" ]; then
          echo "Refresh Token is correct."
        else
          echo "Error: Refresh Token does not match the expected value."
          exit 1
        fi
