name: Check Secrets

on:
  push:
    branches:
      - main

jobs:
  check-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Display Client ID
      run: |
        CLIENT_ID=${{ secrets.CLIENT_ID }}
        echo "Client ID: $CLIENT_ID"
        if [ "$CLIENT_ID" == "62038061756-ot0st3dqt1ekbec5mpbacra9t60k075r.apps.googleusercontent.com" ]; then
          echo "Client ID is correct."
        else
          echo "Error: Client ID does not match the expected value."
          exit 1
        fi
