name: Daily Web Scraping

on: [push]

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify your Python version
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 PyPDF2 google-auth google-api-python-client
      - name: Run scraping script
        run: python your_script3.py  # Replace with your script name
